// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: pb/coordinator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SinceTimeAccArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Acc []int32 `protobuf:"varint,2,rep,packed,name=acc,proto3" json:"acc,omitempty"`
}

func (x *SinceTimeAccArgs) Reset() {
	*x = SinceTimeAccArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SinceTimeAccArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinceTimeAccArgs) ProtoMessage() {}

func (x *SinceTimeAccArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinceTimeAccArgs.ProtoReflect.Descriptor instead.
func (*SinceTimeAccArgs) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *SinceTimeAccArgs) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SinceTimeAccArgs) GetAcc() []int32 {
	if x != nil {
		return x.Acc
	}
	return nil
}

type HeartbeatArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HeartbeatArgs) Reset() {
	*x = HeartbeatArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatArgs) ProtoMessage() {}

func (x *HeartbeatArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatArgs.ProtoReflect.Descriptor instead.
func (*HeartbeatArgs) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatArgs) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RepairTurnArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestEdges int32  `protobuf:"varint,1,opt,name=restEdges,proto3" json:"restEdges,omitempty"`
	Cluster   []byte `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *RepairTurnArgs) Reset() {
	*x = RepairTurnArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepairTurnArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairTurnArgs) ProtoMessage() {}

func (x *RepairTurnArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairTurnArgs.ProtoReflect.Descriptor instead.
func (*RepairTurnArgs) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *RepairTurnArgs) GetRestEdges() int32 {
	if x != nil {
		return x.RestEdges
	}
	return 0
}

func (x *RepairTurnArgs) GetCluster() []byte {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type BalanceCompleteArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineId    int32 `protobuf:"varint,1,opt,name=machineId,proto3" json:"machineId,omitempty"`
	ParentPlanId int32 `protobuf:"varint,2,opt,name=parentPlanId,proto3" json:"parentPlanId,omitempty"`
}

func (x *BalanceCompleteArgs) Reset() {
	*x = BalanceCompleteArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceCompleteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceCompleteArgs) ProtoMessage() {}

func (x *BalanceCompleteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceCompleteArgs.ProtoReflect.Descriptor instead.
func (*BalanceCompleteArgs) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *BalanceCompleteArgs) GetMachineId() int32 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *BalanceCompleteArgs) GetParentPlanId() int32 {
	if x != nil {
		return x.ParentPlanId
	}
	return 0
}

type RegisterArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RegisterArgs) Reset() {
	*x = RegisterArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterArgs) ProtoMessage() {}

func (x *RegisterArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterArgs.ProtoReflect.Descriptor instead.
func (*RegisterArgs) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterArgs) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TCQueryArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query   string  `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Epsilon float64 `protobuf:"fixed64,2,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	Address string  `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *TCQueryArgs) Reset() {
	*x = TCQueryArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCQueryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCQueryArgs) ProtoMessage() {}

func (x *TCQueryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCQueryArgs.ProtoReflect.Descriptor instead.
func (*TCQueryArgs) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *TCQueryArgs) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TCQueryArgs) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *TCQueryArgs) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TCQueryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid  bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Detail string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *TCQueryReply) Reset() {
	*x = TCQueryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCQueryReply) ProtoMessage() {}

func (x *TCQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCQueryReply.ProtoReflect.Descriptor instead.
func (*TCQueryReply) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *TCQueryReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TCQueryReply) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type LPCompleteArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineId int32 `protobuf:"varint,1,opt,name=machineId,proto3" json:"machineId,omitempty"`
	PlanId    int32 `protobuf:"varint,2,opt,name=planId,proto3" json:"planId,omitempty"`
}

func (x *LPCompleteArgs) Reset() {
	*x = LPCompleteArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPCompleteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPCompleteArgs) ProtoMessage() {}

func (x *LPCompleteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPCompleteArgs.ProtoReflect.Descriptor instead.
func (*LPCompleteArgs) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *LPCompleteArgs) GetMachineId() int32 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *LPCompleteArgs) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type LPCompleteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CdComplete bool `protobuf:"varint,1,opt,name=cdComplete,proto3" json:"cdComplete,omitempty"`
}

func (x *LPCompleteReply) Reset() {
	*x = LPCompleteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_coordinator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPCompleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPCompleteReply) ProtoMessage() {}

func (x *LPCompleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_coordinator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPCompleteReply.ProtoReflect.Descriptor instead.
func (*LPCompleteReply) Descriptor() ([]byte, []int) {
	return file_pb_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *LPCompleteReply) GetCdComplete() bool {
	if x != nil {
		return x.CdComplete
	}
	return false
}

var File_pb_coordinator_proto protoreflect.FileDescriptor

var file_pb_coordinator_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x10, 0x53, 0x69, 0x6e, 0x63, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x63, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x61, 0x63, 0x63, 0x22, 0x1f, 0x0a,
	0x0d, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48,
	0x0a, 0x0e, 0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x54, 0x75, 0x72, 0x6e, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x74, 0x45, 0x64, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x73, 0x74, 0x45, 0x64, 0x67, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x57, 0x0a, 0x13, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x49,
	0x64, 0x22, 0x28, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1f, 0x0a, 0x0d, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x0b,
	0x54, 0x43, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x70, 0x73, 0x69, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x65, 0x70, 0x73, 0x69, 0x6c, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x54, 0x43, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x22, 0x46, 0x0a, 0x0e, 0x4c, 0x50, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x4c,
	0x50, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x63, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x32, 0xc3,
	0x04, 0x0a, 0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x38,
	0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x07, 0x54,
	0x43, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x43, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x43, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a, 0x4c,
	0x50, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x50, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x50, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0c, 0x53, 0x69,
	0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x69, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x15, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x15, 0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x54, 0x75, 0x72, 0x6e, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x61,
	0x69, 0x72, 0x54, 0x75, 0x72, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x45, 0x63, 0x63, 0x44, 0x63, 0x72, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_coordinator_proto_rawDescOnce sync.Once
	file_pb_coordinator_proto_rawDescData = file_pb_coordinator_proto_rawDesc
)

func file_pb_coordinator_proto_rawDescGZIP() []byte {
	file_pb_coordinator_proto_rawDescOnce.Do(func() {
		file_pb_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_coordinator_proto_rawDescData)
	})
	return file_pb_coordinator_proto_rawDescData
}

var file_pb_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_coordinator_proto_goTypes = []interface{}{
	(*SinceTimeAccArgs)(nil),    // 0: pb.SinceTimeAccArgs
	(*HeartbeatArgs)(nil),       // 1: pb.HeartbeatArgs
	(*RepairTurnArgs)(nil),      // 2: pb.RepairTurnArgs
	(*BalanceCompleteArgs)(nil), // 3: pb.BalanceCompleteArgs
	(*RegisterArgs)(nil),        // 4: pb.RegisterArgs
	(*RegisterReply)(nil),       // 5: pb.RegisterReply
	(*TCQueryArgs)(nil),         // 6: pb.TCQueryArgs
	(*TCQueryReply)(nil),        // 7: pb.TCQueryReply
	(*LPCompleteArgs)(nil),      // 8: pb.LPCompleteArgs
	(*LPCompleteReply)(nil),     // 9: pb.LPCompleteReply
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
}
var file_pb_coordinator_proto_depIdxs = []int32{
	1,  // 0: pb.Coordinator.Heartbeat:input_type -> pb.HeartbeatArgs
	4,  // 1: pb.Coordinator.Register:input_type -> pb.RegisterArgs
	6,  // 2: pb.Coordinator.TCQuery:input_type -> pb.TCQueryArgs
	8,  // 3: pb.Coordinator.LPComplete:input_type -> pb.LPCompleteArgs
	3,  // 4: pb.Coordinator.BalanceComplete:input_type -> pb.BalanceCompleteArgs
	0,  // 5: pb.Coordinator.SinceTimeAcc:input_type -> pb.SinceTimeAccArgs
	10, // 6: pb.Coordinator.ResultPersistComplete:input_type -> google.protobuf.Empty
	10, // 7: pb.Coordinator.RepairBalanceComplete:input_type -> google.protobuf.Empty
	2,  // 8: pb.Coordinator.RepairTurnComplete:input_type -> pb.RepairTurnArgs
	10, // 9: pb.Coordinator.Heartbeat:output_type -> google.protobuf.Empty
	5,  // 10: pb.Coordinator.Register:output_type -> pb.RegisterReply
	7,  // 11: pb.Coordinator.TCQuery:output_type -> pb.TCQueryReply
	9,  // 12: pb.Coordinator.LPComplete:output_type -> pb.LPCompleteReply
	10, // 13: pb.Coordinator.BalanceComplete:output_type -> google.protobuf.Empty
	10, // 14: pb.Coordinator.SinceTimeAcc:output_type -> google.protobuf.Empty
	10, // 15: pb.Coordinator.ResultPersistComplete:output_type -> google.protobuf.Empty
	10, // 16: pb.Coordinator.RepairBalanceComplete:output_type -> google.protobuf.Empty
	10, // 17: pb.Coordinator.RepairTurnComplete:output_type -> google.protobuf.Empty
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pb_coordinator_proto_init() }
func file_pb_coordinator_proto_init() {
	if File_pb_coordinator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_coordinator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SinceTimeAccArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepairTurnArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceCompleteArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCQueryArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCQueryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPCompleteArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_coordinator_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPCompleteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_coordinator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_coordinator_proto_goTypes,
		DependencyIndexes: file_pb_coordinator_proto_depIdxs,
		MessageInfos:      file_pb_coordinator_proto_msgTypes,
	}.Build()
	File_pb_coordinator_proto = out.File
	file_pb_coordinator_proto_rawDesc = nil
	file_pb_coordinator_proto_goTypes = nil
	file_pb_coordinator_proto_depIdxs = nil
}
